# Parameters:
#   ImageId:
#     Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
#     Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

#   KeyName:
#     Description: Name of an existing EC2 KeyPair to enable SSH access to the instances. Linked to AWS Parameter
#     Type: AWS::EC2::KeyPair::KeyName
#     ConstraintDescription: must be the name of an existing EC2 KeyPair.

#   AZa:
#     Type: AWS::EC2::AvailabilityZone::Name

#   AZb:
#     Type: AWS::EC2::AvailabilityZone::Name

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: AWS-JENKINS-CLOUDFORMATION-OCSD-DEMO
      GroupDescription: allow connections from specified CIDR ranges
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

  # EC2LaunchTemplate:
  #   Type: AWS::EC2::LaunchTemplate
  #   Properties:
  #     LaunchTemplateName: EC2LaunchTemplateforAutoScaling
  #     LaunchTemplateData:
  #       ImageId: !Ref ImageId
  #       InstanceType: t2.micro
  #       KeyName: !Ref KeyName 
  #       SecurityGroups:
  #         - !Ref SecurityGroup
  #       UserData: 
  #         Fn::Base64: |
  #           #!/bin/bash -xe
  #           sudo yum update -y
  #           sudo amazon-linux-extras install nginx1 -y
  #           sudo systemctl enable nginx
  #           sudo systemctl start nginx 

  # AutoSG: 
  #   Type: AWS::AutoScaling::AutoScalingGroup
  #   Properties:
  #     AvailabilityZones: 
  #      - !Ref AZa 
  #      - !Ref AZb 
  #     AutoScalingGroupName: AutoSGForDemo
  #     DesiredCapacity: 1
  #     LaunchTemplate:
  #       LaunchTemplateId: !Ref EC2LaunchTemplate
  #       Version: !GetAtt EC2LaunchTemplate.LatestVersionNumber
  #     MaxSize: 2
  #     MinSize: 1

  # ScheduledActionOut: 
  #   Type: AWS::AutoScaling::ScheduledAction
  #   Properties:
  #     AutoScalingGroupName: !Ref AutoSG
  #     DesiredCapacity: 2
  #     MaxSize: 2
  #     MinSize: 1
  #     Recurrence: "0 7 * * *"

  # ScheduledActionIn: 
  #   Type: AWS::AutoScaling::ScheduledAction
  #   Properties:
  #     AutoScalingGroupName: !Ref AutoSG
  #     DesiredCapacity: 1
  #     MaxSize: 1
  #     MinSize: 1
  #     Recurrence: "0 19 * * *"
      

    
        

